version: '3.9'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8080:8080"
    env_file: ./.env
    restart: always
    volumes:
      - ./:/app