version: '3.9'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./:/app