name: Eslint tests

on:
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [opened, reopened, synchronize]

jobs:
  eslint:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Run eslint
        run: yarn lint > eslint-results

      - name: Get eslint results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: eslint-results
          path: eslint-results
